sudo: required
services:
  - docker

before_install:
  - docker build -t asa297/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run asa297/react-test npm test -- --coverage

after_success:
  - docker build -t asa297/multi-client ./client
  - docker build -t asa297/multi-nginx ./nginx
  - docker build -t asa297/multi-server ./server
  - docker build -t asa297/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push asa297/multi-client
  - docker push asa297/multi-nginx
  - docker push asa297/multi-server
  - docker push asa297/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-253424059284'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
