sudo : required
services :
  - docker

before_install :
  - docker build -t superauman/react-test -f ./client/Dockerfile.dev ./client

script :
  - docker run superauman/react-test npm run test -- --coverage

after_success :
  - docker build -t superauman/client ./client
  - docker build -t superauman/nginx ./nginx
  - docker build -t superauman/server ./server
  - docker build -t superauman/worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push superauman/client
  - docker push superauman/nginx
  - docker push superauman/server
  - docker push superauman/worker
